"""empty message

Revision ID: 017ab30f992b
Revises: 88c093c0f565
Create Date: 2024-12-09 21:03:26.821096

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '017ab30f992b'
down_revision = '88c093c0f565'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('property_listing', schema=None) as batch_op:
        batch_op.add_column(sa.Column('property_state_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key(None, 'state', ['property_state_id'], ['state_id'])
        batch_op.drop_column('state_id')
        batch_op.drop_column('state_name')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('property_listing', schema=None) as batch_op:
        batch_op.add_column(sa.Column('state_name', mysql.VARCHAR(length=100), nullable=False))
        batch_op.add_column(sa.Column('state_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True))
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('property_state_id')

    # ### end Alembic commands ###
