"""empty message

Revision ID: 022b9d4c32f8
Revises: 
Create Date: 2024-12-07 18:21:39.627628

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '022b9d4c32f8'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('admin',
    sa.Column('admin_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('admin_name', sa.String(length=100), nullable=False),
    sa.Column('admin_password', sa.String(length=255), nullable=False),
    sa.Column('admin_email', sa.String(length=100), nullable=False),
    sa.Column('admin_login', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('admin_id')
    )
    op.create_table('property_type',
    sa.Column('property_id', sa.Integer(), nullable=False),
    sa.Column('property_name', sa.String(length=255), nullable=False),
    sa.PrimaryKeyConstraint('property_id')
    )
    op.create_table('property_listing',
    sa.Column('property_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('title', sa.String(length=100), nullable=False),
    sa.Column('description', sa.String(length=100), nullable=False),
    sa.Column('property_price', sa.Float(), nullable=False),
    sa.Column('property_type', sa.Enum('0', '1'), server_default='0', nullable=False),
    sa.Column('property_amenities', sa.Text(), nullable=True),
    sa.Column('property_status', sa.Enum('0', '1'), server_default='0', nullable=False),
    sa.Column('property_cover_picture', sa.String(length=100), nullable=False),
    sa.Column('property_category', sa.String(length=100), server_default='0', nullable=False),
    sa.Column('state_id', sa.Integer(), nullable=True),
    sa.Column('state_name', sa.String(length=100), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user.user_id'], ),
    sa.PrimaryKeyConstraint('property_id')
    )
    op.create_table('saved_properties',
    sa.Column('saved_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('property_id', sa.Integer(), nullable=True),
    sa.Column('saved_date', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user.user_id'], ),
    sa.PrimaryKeyConstraint('saved_id')
    )
    op.create_table('message_table',
    sa.Column('message_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('sender_id', sa.Integer(), nullable=True),
    sa.Column('reciever_id', sa.Integer(), nullable=True),
    sa.Column('property_id', sa.Integer(), nullable=True),
    sa.Column('message_content', sa.Text(), nullable=False),
    sa.Column('timestamp', sa.DateTime(), nullable=True),
    sa.Column('status', sa.Enum('o', '1'), nullable=True),
    sa.ForeignKeyConstraint(['property_id'], ['property_listing.property_id'], ),
    sa.ForeignKeyConstraint(['reciever_id'], ['user.user_id'], ),
    sa.ForeignKeyConstraint(['sender_id'], ['user.user_id'], ),
    sa.PrimaryKeyConstraint('message_id')
    )
    op.create_table('reviews_ratings',
    sa.Column('review_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('property_id', sa.Integer(), nullable=True),
    sa.Column('rating', sa.Integer(), nullable=False),
    sa.Column('review_text', sa.Text(), nullable=False),
    sa.Column('timestamp', sa.DateTime(), nullable=True),
    sa.Column('review_status', sa.Enum('o', '1'), nullable=True),
    sa.ForeignKeyConstraint(['property_id'], ['property_listing.property_id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.user_id'], ),
    sa.PrimaryKeyConstraint('review_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('reviews_ratings')
    op.drop_table('message_table')
    op.drop_table('saved_properties')
    op.drop_table('property_listing')
    op.drop_table('property_type')
    op.drop_table('admin')
    # ### end Alembic commands ###
