"""empty message

Revision ID: 124cec116adc
Revises: 4c84646e2dd6
Create Date: 2024-12-10 08:23:00.803373

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '124cec116adc'
down_revision = '4c84646e2dd6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('property_listing', schema=None) as batch_op:
        batch_op.alter_column('property_status',
               existing_type=mysql.ENUM('0', '1'),
               type_=sa.Enum('Available', 'Unavailable'),
               existing_nullable=False,
               existing_server_default=sa.text("'Available'"))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('property_listing', schema=None) as batch_op:
        batch_op.alter_column('property_status',
               existing_type=sa.Enum('Available', 'Unavailable'),
               type_=mysql.ENUM('0', '1'),
               existing_nullable=False,
               existing_server_default=sa.text("'0'"))

    # ### end Alembic commands ###
