"""empty message

Revision ID: 4c84646e2dd6
Revises: 017ab30f992b
Create Date: 2024-12-10 08:20:55.749566

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4c84646e2dd6'
down_revision = '017ab30f992b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('user_status', sa.Enum('Active', 'Inactive'), server_default='Active', nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_column('user_status')

    # ### end Alembic commands ###
