"""empty message

Revision ID: 60828e91ef2d
Revises: cb2f7fe59b9f
Create Date: 2024-12-08 12:22:56.928580

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '60828e91ef2d'
down_revision = 'cb2f7fe59b9f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.create_unique_constraint(None, ['user_number'])
        batch_op.create_unique_constraint(None, ['user_email'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='unique')
        batch_op.drop_constraint(None, type_='unique')

    # ### end Alembic commands ###
