"""empty message

Revision ID: cfbb62239076
Revises: f8fc8c27ef77
Create Date: 2024-12-19 21:42:26.403847

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'cfbb62239076'
down_revision = 'f8fc8c27ef77'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('reviews_ratings')
    with op.batch_alter_table('property_listing', schema=None) as batch_op:
        batch_op.add_column(sa.Column('bedroom_number', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('bathroom_number', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('parking_space', sa.Integer(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('property_listing', schema=None) as batch_op:
        batch_op.drop_column('parking_space')
        batch_op.drop_column('bathroom_number')
        batch_op.drop_column('bedroom_number')

    op.create_table('reviews_ratings',
    sa.Column('review_id', mysql.INTEGER(display_width=11), autoincrement=True, nullable=False),
    sa.Column('user_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True),
    sa.Column('property_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True),
    sa.Column('rating', mysql.INTEGER(display_width=11), autoincrement=False, nullable=False),
    sa.Column('review_text', mysql.TEXT(), nullable=False),
    sa.Column('timestamp', mysql.DATETIME(), nullable=True),
    sa.Column('review_status', mysql.ENUM('o', '1'), nullable=True),
    sa.ForeignKeyConstraint(['property_id'], ['property_listing.property_id'], name='reviews_ratings_ibfk_1'),
    sa.ForeignKeyConstraint(['user_id'], ['user.user_id'], name='reviews_ratings_ibfk_2'),
    sa.PrimaryKeyConstraint('review_id'),
    mysql_collate='utf8mb4_general_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    # ### end Alembic commands ###
