"""empty message

Revision ID: e9bb35190df1
Revises: cfbb62239076
Create Date: 2024-12-20 00:57:15.868781

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'e9bb35190df1'
down_revision = 'cfbb62239076'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('saved_properties')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('saved_properties',
    sa.Column('saved_id', mysql.INTEGER(display_width=11), autoincrement=True, nullable=False),
    sa.Column('user_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True),
    sa.Column('property_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True),
    sa.Column('saved_date', mysql.DATETIME(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user.user_id'], name='saved_properties_ibfk_1'),
    sa.PrimaryKeyConstraint('saved_id'),
    mysql_collate='utf8mb4_general_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    # ### end Alembic commands ###
