"""empty message

Revision ID: f4e7e46efb32
Revises: 124cec116adc
Create Date: 2024-12-10 08:47:31.120453

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'f4e7e46efb32'
down_revision = '124cec116adc'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('property_listing', schema=None) as batch_op:
        batch_op.drop_column('state_id')
        batch_op.drop_column('state_name')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('property_listing', schema=None) as batch_op:
        batch_op.add_column(sa.Column('state_name', mysql.VARCHAR(length=100), nullable=False))
        batch_op.add_column(sa.Column('state_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True))

    # ### end Alembic commands ###
