"""empty message

Revision ID: f8fc8c27ef77
Revises: f4e7e46efb32
Create Date: 2024-12-19 11:12:48.673946

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f8fc8c27ef77'
down_revision = 'f4e7e46efb32'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('property_image',
    sa.Column('image_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('property_id', sa.Integer(), nullable=True),
    sa.Column('property_picture', sa.String(length=100), nullable=False),
    sa.ForeignKeyConstraint(['property_id'], ['property_listing.property_id'], ),
    sa.PrimaryKeyConstraint('image_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('property_image')
    # ### end Alembic commands ###
